#!/usr/bin/env bash
#
# This script extracts the pieces that we need to compile our bridge line.
# This will have to do until the following bug is fixed:
# <https://bugs.torproject.org/30331>

TOR_LOG=/var/log/tor/log
PT_STATE=/var/lib/tor/pt_state/obfs4_bridgeline.txt

if [ ! -r "$TOR_LOG" ]
then
    echo "Cannot read Tor's log file ${TOR_LOG}. This is a bug."
    exit 1
fi

if [ ! -r "$PT_STATE" ]
then
    echo "Cannot read PT state file ${TOR_LOG}. This is a bug."
    exit 1
fi

addr=$(grep 'Guessed our IP address' "$TOR_LOG" | \
    sed 's/.* \([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\) .*/\1/')
port=$(grep "Registered server transport 'obfs4' at" "$TOR_LOG" | \
    sed "s/.*:\([0-9]\{1,5\}\)'$/\1/")
fingerprint=$(grep "Your Tor server's identity key fingerprint is" "$TOR_LOG" | \
    sed "s/.*\([0-9A-F]\{40\}\)'$/\1/")
obfs4_args=$(grep '^Bridge obfs4' "$PT_STATE" | sed 's/.*\(cert=.*\)/\1/')

if [[ "$addr" = "" || "$port" = "" || "$fingerprint" = "" || "$obfs4_args" = "" ]]
then
    echo "Could not create bridge line. Tor's log format may have changed. This is a bug."
    exit 1
fi

echo "obfs4 ${addr}:${port} ${fingerprint} ${obfs4_args}"
