name: 'Test and deploy obfs4-bridge docker image.'

on:
  repository_dispatch:
    types: new-release

# This variables are required in order to start the container and have the
# bootstrap phase succeed.
env:
  OR_PORT: 1050
  PT_PORT: 1051
  EMAIL: testing_bridge@email.org

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Source environmental variables from file
        run: |
          cat .env | grep IMAGE= | head -n 1 | sed "s/IMAGE=//" > IMAGE

      # If the multiarch patch will be merged, this can be extended for test
      # every images; otherwise can be set up one job for each architecture.
      - name: Build obfs4-bridge image
        run: docker build -f Dockerfile -t $(cat IMAGE) .

      # Starts the container with random pots and invalid email, it is required
      # in order to test the bootstrap phase.
      - name: Start container and copy test file into
        run: |
          docker run -d --env "OR_PORT=${OR_PORT}" --env "PT_PORT=${PT_PORT}" --env "EMAIL=${EMAIL}" --name testing $(cat IMAGE)
          docker cp test.sh testing:/test.sh
      - name: Run test
        run: docker exec testing bash /test.sh
  
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      # Actually is here that the variables are set as environmental in order
      # to be available for the Makefile.
      # This can be used also in the test job which allows to replace $(cat VAR)
      # into simple ${VAR}
      - name: Source and set environmental variables.
        run: |
          cat .env | grep IMAGE= | head -n 1 | sed "s/IMAGE=//" > IMAGE
          echo "::set-env name=IMAGE::$(cat IMAGE)"
          echo "::set-env name=VERSION::${{ github.event.client_payload.version }}"
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: make build

      - name: Release
        run: |
          make tag
          make release
